name: Deploy with Docker Compose

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      SSH_PORT: ${{ vars.SSH_PORT }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        source: "."
        target: "/home/${{ env.SSH_USERNAME }}/docker-compose-deploy-action-example"
        rm: true
        
    - name: Install Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          # Install Docker if not exists
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            rm get-docker.sh
            echo "Docker installed successfully"
          else
            echo "Docker is already installed"
          fi
          docker --version
          
          # Start Docker service if not running
          if ! sudo systemctl is-active docker &> /dev/null; then
            echo "Starting Docker service..."
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

    - name: Setup Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          # Detect which Docker Compose command to use
          if docker compose version &> /dev/null; then
            echo "COMPOSE_CMD=docker compose" >> ~/.compose_env
            echo "Using modern docker compose"
            docker compose version
          elif command -v docker-compose &> /dev/null; then
            echo "COMPOSE_CMD=docker-compose" >> ~/.compose_env
            echo "Using legacy docker-compose"
            docker-compose --version
          else
            echo "Installing docker-compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            echo "COMPOSE_CMD=docker-compose" >> ~/.compose_env
            docker-compose --version
          fi
          
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          cd /home/${{ env.SSH_USERNAME }}/docker-compose-deploy-action-example
          
          # Detect which Docker Compose command to use in this session
          if docker compose version &> /dev/null; then
            COMPOSE_CMD="docker compose"
            echo "Using modern docker compose"
          elif command -v docker-compose &> /dev/null; then
            COMPOSE_CMD="docker-compose"
            echo "Using legacy docker-compose"
          else
            echo "ERROR: No Docker Compose found!"
            exit 1
          fi
          
          $COMPOSE_CMD down
          $COMPOSE_CMD up -d
          $COMPOSE_CMD ps