name: Deploy with Docker Compose

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      SSH_PORT: ${{ vars.SSH_PORT }}
      TARGET_DIR: ${{ vars.TARGET_DIR || '/opt/kharkov-apartment-production' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ env.SSH_PORT }}
        source: "."
        target: "${{ env.TARGET_DIR }}"
        rm: true

    - name: Install Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ env.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIR }}
          ./github-workflow-scripts/install-docker.sh

    - name: Setup Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ env.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIR }}
          ./github-workflow-scripts/setup-docker-compose.sh

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ env.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIR }}
          TARGET_DIR=${{ env.TARGET_DIR }} ./github-workflow-scripts/deploy.sh
